### ISSUE TITLE
Question | connectionStrings 

### ISSUE THREAD

**Issue by goncalosilvalaranjeira** [DynamicsNinja/MultiplexingServiceClient#1]
What happens if  "your-connection-string-1" equals "your-connection-string-2"? Does it make sense to do it? to maximize the number of connectionStrings, or is it redundant?

var connectionStrings = new List<string>
{
    "your-connection-string-1",
    "your-connection-string-2"
};

N.B. This is not a issue but a question.

**Comment by DynamicsNinja** [comment]
It doesn't make sense to use the same connection string here. You should create multiple application users and use connection string per application user.

**Comment by goncalosilvalaranjeira** [comment]
Thank you for your reply. Using a single connection might not be ideal, but even with just one connection string, your framework will still lead to an overall improvement, right?

**Comment by DynamicsNinja** [comment]
You could see improvement with a single connection too, but it's designed to improve performance with multiple application users.
